spring:
  application:
    name: worklog-compliance-batch

  datasource:
    url: jdbc:postgresql://localhost:5432/worklog
    username: postgres
    password: prefab2022

  batch:
    job:
      name: worklogImportJob
      enabled: true
    jdbc:
      initialize-schema: never

logging:
  level:
#    org.springframework.jdbc.datasource.init: DEBUG
#    org.springframework.batch: DEBUG
#    org.springframework.jdbc.core: DEBUG

worklog:
  expected-hours-per-day: 9